use .eslintrc instead of CFU (#3725)
* improvement: use .eslintrc

* improvement: eslint update

* fix: browserlist warning

* improvement: skip eslint in rollup

* fix: ts & stylus err

* fix: stylus update

* fix: enable lint in dev env

* test: stylus update

* fix: stylus

* Ci lint (#3726)

* improvement: github action for eslint

* error code

* error code

* test

* test 2

* test

* test 3

* pr

* test <

* pwd

* home set

* another test

* fix: eslint

* test

* github-pr-check

* fix: test file

* improvement: enforce pre commit lint

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* fix: comments & eslint rules

* tsconfig update

* fix: disable no-undef

* fix: upi.ts

* fix: types

* fix: comment validate

* track only error

* fix: eslint error

* disable fail on error

* fix: lint

* fix: eslint autofix --fix (#3736)

* fix: eslint fixable issue

* improvement: eslint fixes

* fix: eslint errors [part 2] (#3739)

* fix: eslint errors

* fix: eslint errors p3

Co-authored-by: Arshpreet <me@wadehrarshpreet.com>

Co-authored-by: Arshpreet <me@wadehrarshpreet.com>

* Update loadScript.js

* Update constants.ts

Co-authored-by: Arshpreet <me@wadehrarshpreet.com>

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -25,9 +25,10 @@ echo "${CYAN} Linting...🔍"
 ./node_modules/.bin/eslint --fix ${fileList[*]}
 if [ $? -ne 0 ]
 then  
-  echo "${YELLOW} Surpassing lint errors please fix ASAP"
+  # echo "${YELLOW} Surpassing lint errors please fix ASAP"
   # enable the following when eslint failure has to stop commiting
-  # echo -e "\nPlease fix the above linting issues before committing.\n"
+  echo -e "\nPlease fix the above linting issues before committing.\n"
+  exit 1
 fi 
 
 
