success-failure status github action (#2593)
* success-failure status github action

* feat: success failure status checks config modifed.

* indentation fix

* fix

Co-authored-by: nandakishorjeripothula <jeripothula.kishor@razorpay.com>

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -20,16 +20,19 @@ jobs:
           echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
           echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
       - name: Set up Docker Buildx
+        id: docker
         uses: docker/setup-buildx-action@v1
         with:
           install: true
       - name: Login to Harbor
+        id: harbor
         uses: docker/login-action@v1
         with:
           registry: c.rzp.io
           username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
           password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
       - name: Build and push
+        id: build
         uses: docker/build-push-action@v2
         with:
           file: ./Dockerfile
@@ -51,3 +54,20 @@ jobs:
             "GIT_COMMIT_HASH=${{ github.sha }}"
           push: true
           tags: c.rzp.io/razorpay/checkout:${{ github.sha }}
+      - name: Mark workflow status as failed
+        id: failed
+        if: steps.vars.outcome != 'success' || steps.docker.outcome != 'success' || steps.harbor.outcome != 'success' || steps.build.outcome != 'success'
+        run: |
+          echo 'Failing the workflow for github status check.'
+          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
+          -d '{ "state" : "failure" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
+          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
+          exit 1
+      - name: Mark workflow status as success
+        if: steps.failed.conclusion == 'skipped'
+        run: |
+          echo 'Status check has passed!'
+          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
+          -d '{ "state" : "success" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
+          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
+          exit 0
